config/routes.rb
Rails.application.routes.draw do
  root 'pages#hello'
  get 'about', to: 'pages#about'
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  # above is the same as below..above we have seen all he http routes
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates:title, presence: true, length:{minimum: 6,maximum: 100}
    validates:description, presence: true, length:{minimum: 10,miximum: 150} 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # def hello
    #     render html: 'hello world!'
    # end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def show
        # byebug
        @article = Article.find(params[:id])
    end
    def index
        @articles=Article.all
    end
    def new
        @article = Article.new
    end
    def edit
        @article = Article.find(params[:id])
    end
    def create
        @article = Article.new(params.require(:article).permit(:title, :description))
        # render plain: @article.inspect
        if @article.save
            flash[:notice]="Article was created successfully."
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end
    def update
        @article = Article.find(params[:id])
        if @article.update(params.require(:article).permit(:title, :description))
            flash[:notice]="Article is updated Successfully"
            redirect_to @article
        else
            render 'edit'
        end
    end
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def hello
    end
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<% if @article.errors.any?%>
    <h3>There are some error in it</h3>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %><li>
    <% end %>
    </ul>
<% end %>
<%= form_with(model: @article, local: true) do |f|%>
    <p>
        <%= f.label :title%><br/>
        <%= f.text_field :title%>
    </p>
    <p>
        <%= f.label :description%><br/>
        <%= f.text_area :description%>
    </p>
    <p>
        <%= f.submit%>
    </p>
<% end %>
<%= link_to 'Cancle Edit and Return back to Listing', article_path %>

app/views/articles/index.html.erb
<h1>Listing of all the Articles</h1>
<table>
    <thead>
        <tr>
            <th>TitLe</th>
            <th>Description</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.title%></td>
                <td><%= article.description%></td>
                <td><%= link_to 'SHOW', article_path(article.id) %></td>
                <td><%= link_to 'EDIT', edit_article_path(article.id) %></td>
                <td><%= link_to 'DELETE', article_path(article.id), method: :delete, data: {confirm: "Are you Sure"} %></td>
            </tr>
        <% end %>
    </tbody>
</table>
<p><%= link_to 'Add New Article', new_article_path%></p>

app/views/articles/new.html.erb
<h1>Create New Article</h1>
<% if @article.errors.any?%>
    <h3>There are some error in it</h3>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %><li>
    <% end %>
    </ul>
<% end %>
<%= form_with scope: :article, url: articles_path, local: true do |f|%>
    <p>
        <%= f.label :title%><br/>
        <%= f.text_field :title%>
    </p>
    <p>
        <%= f.label :description%><br/>
        <%= f.text_area :description%>
    </p>
    <p>
        <%= f.submit%>
    </p>
<% end %>

app/views/articles/show.html.erb
<h1>SHOWING</h1>
<p><strong>Title:</strong> <%= @article.title%></p>
<p><strong>Description:</strong> <%= @article.description%></p>
<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Delete', edit_article_path(@article), method: :delete, data: {confirm: "Are you Sure"} %>
<%= link_to 'Return to Listing', articles_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |name, msg|%>
    <%= msg %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Hi this is about page</h1>
<%= link_to 'Show Listing', articles_path%>
<%= link_to 'Hello', root_path%>

app/views/pages/hello.html.erb
<h1>Hello World</h1>
<%= link_to 'Show Listing', articles_path%>
<%= link_to 'About', about_path%>